# Generated by Django 4.2.6 on 2024-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('P_Price', models.IntegerField(blank=True, null=True)),
                ('P_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('P_Image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
