# Generated by Django 5.0.1 on 2024-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_flightbookingdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedb',
            name='Destination_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
