# Generated by Django 5.0.1 on 2024-03-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_placedb_destination_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedb',
            old_name='Destination_Name',
            new_name='Name',
        ),
    ]
