# Generated by Django 5.0.1 on 2024-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_destination_name_placedb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='singleDestinationBd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('From_To', models.CharField(blank=True, max_length=50, null=True)),
                ('Duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Place_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
