# Generated by Django 5.0.1 on 2024-03-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_singledestinationbd'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledestinationbd',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
