# Generated by Django 5.0.1 on 2024-03-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_singledes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedb',
            name='Name',
        ),
        migrations.AddField(
            model_name='placedb',
            name='modeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.destinationdb'),
        ),
    ]
