# Generated by Django 5.0.1 on 2024-03-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_remove_placedb_name_placedb_modename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleDes',
        ),
        migrations.RenameField(
            model_name='placedb',
            old_name='P_Name',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='singledestinationbd',
            name='category',
        ),
        migrations.AddField(
            model_name='singledestinationbd',
            name='modeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.destinationdb'),
        ),
        migrations.AddField(
            model_name='singledestinationbd',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.placedb'),
        ),
    ]
