# Generated by Django 5.0.1 on 2024-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_delete_singledes_rename_p_name_placedb_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedb',
            name='P_Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
