# Generated by Django 5.0.1 on 2024-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_placedb_p_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledestinationbd',
            name='From_To',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
