# Generated by Django 5.0.1 on 2024-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_singledestinationbd_from_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledestinationbd',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
