# Generated by Django 5.0.1 on 2024-03-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledestinationbd',
            name='PlaceName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
