# Generated by Django 5.0.1 on 2024-03-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_hotels_hotel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurants_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Restaurants_Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Restaurants_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.singledestinationbd')),
            ],
        ),
    ]
