# Generated by Django 5.0.1 on 2024-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_remove_restaurants_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='Restaurants_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
