# Generated by Django 5.0.1 on 2024-03-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_restaurants_restaurants_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingdb',
            name='From',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingdb',
            name='To',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingdb',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.singledestinationbd'),
        ),
    ]
