# Generated by Django 5.0.1 on 2024-03-14 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_flightbookingdb_from_flightbookingdb_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_price', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Total_price', models.IntegerField(blank=True, max_length=50, null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.singledestinationbd')),
            ],
        ),
    ]
