# Generated by Django 5.0.3 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Hotel_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
