# Generated by Django 5.0.1 on 2024-03-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
