# Generated by Django 5.0.3 on 2024-03-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_save_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.userlogindb'),
        ),
    ]
