# Generated by Django 5.0.3 on 2024-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_save_details_price_save_details_single_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
