# Generated by Django 5.0.3 on 2024-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_save_details_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_details',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
    ]
