# Generated by Django 5.0.3 on 2024-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_save_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_details',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
