# Generated by Django 5.0.3 on 2024-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_alter_save_details_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_details',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
