# Generated by Django 5.0.3 on 2024-03-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_save_details_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_details',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
